/* Generated by GOB (v2.0.15)   (do not edit directly) */

#ifndef __GNOME_PILOT_CONDUIT_MANAGEMENT_PRIVATE_H__
#define __GNOME_PILOT_CONDUIT_MANAGEMENT_PRIVATE_H__

#include "gnome-pilot-conduit-management.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GnomePilotConduitManagementPrivate {
#line 120 "gnome-pilot-conduit-management.gob"
	gboolean loaded;
#line 123 "gnome-pilot-conduit-management.gob"
	GModule * dlhandle;
#line 127 "gnome-pilot-conduit-management.gob"
	GnomePilotConduitOldLoadFunc old_load_func;
#line 128 "gnome-pilot-conduit-management.gob"
	GnomePilotConduitLoadFunc load_func;
#line 129 "gnome-pilot-conduit-management.gob"
	GnomePilotConduitDestroyFunc destroy_func;
#line 133 "gnome-pilot-conduit-management.gob"
	GnomePilotConduitMgmtData * mgmtdata;
#line 26 "gnome-pilot-conduit-management-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
