/* Generated by GOB (v2.0.15)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 15

#define selfp (self->_priv)

#include <string.h> /* memset() */

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 30 "gnome-pilot-conduit.gob"

#include <gnome.h>
#include "gnome-pilot-conduit.h"
#include "gnome-pilot-conduit-private.h"
#include <sys/stat.h>
#include <unistd.h>
#include <sys/types.h>
#include <utime.h>
#include <pi-file.h>
#include <math.h>

typedef enum {
	GPC_MSG, GPC_ERR, GPC_WARN
} GPC_MessageType;

#line 38 "gnome-pilot-conduit.c"
/* self casting macros */
#define SELF(x) GNOME_PILOT_CONDUIT(x)
#define SELF_CONST(x) GNOME_PILOT_CONDUIT_CONST(x)
#define IS_SELF(x) GNOME_IS_PILOT_CONDUIT(x)
#define TYPE_SELF GNOME_TYPE_PILOT_CONDUIT
#define SELF_CLASS(x) GNOME_PILOT_CONDUIT_CLASS(x)

#define SELF_GET_CLASS(x) GNOME_PILOT_CONDUIT_GET_CLASS(x)

/* self typedefs */
typedef GnomePilotConduit Self;
typedef GnomePilotConduitClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void gnome_pilot_conduit_class_init (GnomePilotConduitClass * c) G_GNUC_UNUSED;
static void gnome_pilot_conduit_init (GnomePilotConduit * self) G_GNUC_UNUSED;
static void gnome_pilot_conduit_do_send_message (GnomePilotConduit * self, GPC_MessageType t, gchar * message, va_list ap) G_GNUC_UNUSED;
static int ___real_gnome_pilot_conduit_create_settings_window (GnomePilotConduit * self, GtkWidget * parent);

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__progress(object,func,data)	gnome_pilot_conduit_connect__progress((object),(func),(data))
#define self_connect_after__progress(object,func,data)	gnome_pilot_conduit_connect_after__progress((object),(func),(data))
#define self_connect_data__progress(object,func,data,destroy_data,flags)	gnome_pilot_conduit_connect_data__progress((object),(func),(data),(destroy_data),(flags))
#define self_connect__message(object,func,data)	gnome_pilot_conduit_connect__message((object),(func),(data))
#define self_connect_after__message(object,func,data)	gnome_pilot_conduit_connect_after__message((object),(func),(data))
#define self_connect_data__message(object,func,data,destroy_data,flags)	gnome_pilot_conduit_connect_data__message((object),(func),(data),(destroy_data),(flags))
#define self_connect__warning(object,func,data)	gnome_pilot_conduit_connect__warning((object),(func),(data))
#define self_connect_after__warning(object,func,data)	gnome_pilot_conduit_connect_after__warning((object),(func),(data))
#define self_connect_data__warning(object,func,data,destroy_data,flags)	gnome_pilot_conduit_connect_data__warning((object),(func),(data),(destroy_data),(flags))
#define self_connect__error(object,func,data)	gnome_pilot_conduit_connect__error((object),(func),(data))
#define self_connect_after__error(object,func,data)	gnome_pilot_conduit_connect_after__error((object),(func),(data))
#define self_connect_data__error(object,func,data,destroy_data,flags)	gnome_pilot_conduit_connect_data__error((object),(func),(data),(destroy_data),(flags))
#define self_connect__create_settings_window(object,func,data)	gnome_pilot_conduit_connect__create_settings_window((object),(func),(data))
#define self_connect_after__create_settings_window(object,func,data)	gnome_pilot_conduit_connect_after__create_settings_window((object),(func),(data))
#define self_connect_data__create_settings_window(object,func,data,destroy_data,flags)	gnome_pilot_conduit_connect_data__create_settings_window((object),(func),(data),(destroy_data),(flags))
#define self_connect__display_settings(object,func,data)	gnome_pilot_conduit_connect__display_settings((object),(func),(data))
#define self_connect_after__display_settings(object,func,data)	gnome_pilot_conduit_connect_after__display_settings((object),(func),(data))
#define self_connect_data__display_settings(object,func,data,destroy_data,flags)	gnome_pilot_conduit_connect_data__display_settings((object),(func),(data),(destroy_data),(flags))
#define self_connect__save_settings(object,func,data)	gnome_pilot_conduit_connect__save_settings((object),(func),(data))
#define self_connect_after__save_settings(object,func,data)	gnome_pilot_conduit_connect_after__save_settings((object),(func),(data))
#define self_connect_data__save_settings(object,func,data,destroy_data,flags)	gnome_pilot_conduit_connect_data__save_settings((object),(func),(data),(destroy_data),(flags))
#define self_connect__revert_settings(object,func,data)	gnome_pilot_conduit_connect__revert_settings((object),(func),(data))
#define self_connect_after__revert_settings(object,func,data)	gnome_pilot_conduit_connect_after__revert_settings((object),(func),(data))
#define self_connect_data__revert_settings(object,func,data,destroy_data,flags)	gnome_pilot_conduit_connect_data__revert_settings((object),(func),(data),(destroy_data),(flags))

typedef void  (*___Sig1) (GnomePilotConduit *, gint , gint , gpointer);

static void
___marshal_Sig1 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	register ___Sig1 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 3);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig1) (marshal_data != NULL ? marshal_data : cc->callback);

	callback ((GnomePilotConduit *)data1,
		(gint ) g_value_get_int (param_values + 1),
		(gint ) g_value_get_int (param_values + 2),
		data2);
}


typedef void  (*___Sig2) (GnomePilotConduit *, gpointer , gpointer);

static void
___marshal_Sig2 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	register ___Sig2 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 2);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig2) (marshal_data != NULL ? marshal_data : cc->callback);

	callback ((GnomePilotConduit *)data1,
		(gpointer ) g_value_get_pointer (param_values + 1),
		data2);
}


typedef gint  (*___Sig3) (GnomePilotConduit *, gpointer , gpointer);

static void
___marshal_Sig3 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	gint  v_return;
	register ___Sig3 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 2);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig3) (marshal_data != NULL ? marshal_data : cc->callback);

	v_return = callback ((GnomePilotConduit *)data1,
		(gpointer ) g_value_get_pointer (param_values + 1),
		data2);

	g_value_set_int (return_value, v_return);
}


enum {
	PROGRESS_SIGNAL,
	MESSAGE_SIGNAL,
	WARNING_SIGNAL,
	ERROR_SIGNAL,
	CREATE_SETTINGS_WINDOW_SIGNAL,
	DISPLAY_SETTINGS_SIGNAL,
	SAVE_SETTINGS_SIGNAL,
	REVERT_SETTINGS_SIGNAL,
	LAST_SIGNAL
};

enum {
	PROP_0,
	PROP_NAME,
	PROP_PROGRESS_STEPPING,
	PROP_PROGRESS_TOP,
	PROP_PILOT
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GtkObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_name gnome_pilot_conduit_get_name
#define self_set_name gnome_pilot_conduit_set_name
#define self_new gnome_pilot_conduit_new
#define self_progress gnome_pilot_conduit_progress
#define self_send_progress gnome_pilot_conduit_send_progress
#define self_message gnome_pilot_conduit_message
#define self_warning gnome_pilot_conduit_warning
#define self_error gnome_pilot_conduit_error
#define self_do_send_message gnome_pilot_conduit_do_send_message
#define self_send_message gnome_pilot_conduit_send_message
#define self_send_warning gnome_pilot_conduit_send_warning
#define self_send_error gnome_pilot_conduit_send_error
#define self_create_settings_window gnome_pilot_conduit_create_settings_window
#define self_display_settings gnome_pilot_conduit_display_settings
#define self_save_settings gnome_pilot_conduit_save_settings
#define self_revert_settings gnome_pilot_conduit_revert_settings
#define self_get_base_dir gnome_pilot_conduit_get_base_dir
GType
gnome_pilot_conduit_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GnomePilotConduitClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) gnome_pilot_conduit_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GnomePilotConduit),
			0 /* n_preallocs */,
			(GInstanceInitFunc) gnome_pilot_conduit_init,
			NULL
		};

		type = g_type_register_static (GTK_TYPE_OBJECT, "GnomePilotConduit", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GnomePilotConduit *)g_object_new(gnome_pilot_conduit_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GnomePilotConduit * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GnomePilotConduit *
GET_NEW_VARG (const char *first, ...)
{
	GnomePilotConduit *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GnomePilotConduit *)g_object_new_valist (gnome_pilot_conduit_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::finalize"
	GnomePilotConduit *self G_GNUC_UNUSED = GNOME_PILOT_CONDUIT (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 47 "gnome-pilot-conduit.gob"
	if(self->name) { g_free ((gpointer) self->name); self->name = NULL; }
#line 283 "gnome-pilot-conduit.c"
}
#undef __GOB_FUNCTION__

static void 
gnome_pilot_conduit_class_init (GnomePilotConduitClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (GTK_TYPE_OBJECT);

	object_signals[PROGRESS_SIGNAL] =
		g_signal_new ("progress",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitClass, progress),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_NONE, 2,
			G_TYPE_INT,
			G_TYPE_INT);
	if ___GOB_UNLIKELY(sizeof(gint ) != sizeof(gint ) || sizeof(gint ) != sizeof(gint ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit.gob line 71: Type mismatch of \"progress\" signal signature");
	}
	object_signals[MESSAGE_SIGNAL] =
		g_signal_new ("message",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitClass, message),
			NULL, NULL,
			___marshal_Sig2,
			G_TYPE_NONE, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(gchar * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit.gob line 113: Type mismatch of \"message\" signal signature");
	}
	object_signals[WARNING_SIGNAL] =
		g_signal_new ("warning",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitClass, warning),
			NULL, NULL,
			___marshal_Sig2,
			G_TYPE_NONE, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(gchar * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit.gob line 117: Type mismatch of \"warning\" signal signature");
	}
	object_signals[ERROR_SIGNAL] =
		g_signal_new ("error",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitClass, error),
			NULL, NULL,
			___marshal_Sig2,
			G_TYPE_NONE, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(gchar * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit.gob line 121: Type mismatch of \"error\" signal signature");
	}
	object_signals[CREATE_SETTINGS_WINDOW_SIGNAL] =
		g_signal_new ("create_settings_window",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitClass, create_settings_window),
			NULL, NULL,
			___marshal_Sig3,
			G_TYPE_INT, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(GtkWidget * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit.gob line 167: Type mismatch of \"create_settings_window\" signal signature");
	}
	object_signals[DISPLAY_SETTINGS_SIGNAL] =
		g_signal_new ("display_settings",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitClass, display_settings),
			NULL, NULL,
			g_cclosure_marshal_VOID__VOID,
			G_TYPE_NONE, 0);
	object_signals[SAVE_SETTINGS_SIGNAL] =
		g_signal_new ("save_settings",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitClass, save_settings),
			NULL, NULL,
			g_cclosure_marshal_VOID__VOID,
			G_TYPE_NONE, 0);
	object_signals[REVERT_SETTINGS_SIGNAL] =
		g_signal_new ("revert_settings",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitClass, revert_settings),
			NULL, NULL,
			g_cclosure_marshal_VOID__VOID,
			G_TYPE_NONE, 0);

	c->progress = NULL;
	c->message = NULL;
	c->warning = NULL;
	c->error = NULL;
#line 167 "gnome-pilot-conduit.gob"
	c->create_settings_window = ___real_gnome_pilot_conduit_create_settings_window;
#line 387 "gnome-pilot-conduit.c"
	c->display_settings = NULL;
	c->save_settings = NULL;
	c->revert_settings = NULL;
	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string ("name", NULL, NULL,
		NULL,
		(GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_NAME, param_spec);
	param_spec = g_param_spec_int ("progress_stepping", NULL, NULL,
		G_MININT, G_MAXINT,
		0,
		(GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_PROGRESS_STEPPING, param_spec);
	param_spec = g_param_spec_int ("progress_top", NULL, NULL,
		G_MININT, G_MAXINT,
		0,
		(GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_PROGRESS_TOP, param_spec);
	param_spec = g_param_spec_pointer ("pilot", NULL, NULL,
		(GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_PILOT, param_spec);
    }
}
#undef __GOB_FUNCTION__
#line 59 "gnome-pilot-conduit.gob"
static void 
gnome_pilot_conduit_init (GnomePilotConduit * self G_GNUC_UNUSED)
#line 424 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::init"
 {
#line 59 "gnome-pilot-conduit.gob"

		self->progress_top = 0;
		self->progress_stepping = 0;
		self->name = NULL;
	
#line 434 "gnome-pilot-conduit.c"
 }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::set_property"
{
	GnomePilotConduit *self G_GNUC_UNUSED;

	self = GNOME_PILOT_CONDUIT (object);

	switch (property_id) {
	case PROP_NAME:
	{	gchar *  ARG G_GNUC_UNUSED = (gchar * ) g_value_get_string (VAL);
		{
#line 48 "gnome-pilot-conduit.gob"
g_free (self->name); self->name = g_strdup (ARG);
#line 456 "gnome-pilot-conduit.c"
		}
		break;
	}
	case PROP_PROGRESS_STEPPING:
	{	gint  ARG G_GNUC_UNUSED = (gint ) g_value_get_int (VAL);
		{
#line 51 "gnome-pilot-conduit.gob"
self->progress_stepping = ARG;
#line 465 "gnome-pilot-conduit.c"
		}
		break;
	}
	case PROP_PROGRESS_TOP:
	{	gint  ARG G_GNUC_UNUSED = (gint ) g_value_get_int (VAL);
		{
#line 54 "gnome-pilot-conduit.gob"
self->progress_top = ARG;
#line 474 "gnome-pilot-conduit.c"
		}
		break;
	}
	case PROP_PILOT:
	{	GPilotPilot *  ARG G_GNUC_UNUSED = (GPilotPilot * ) g_value_get_pointer (VAL);
		{
#line 57 "gnome-pilot-conduit.gob"
self->pilot = ARG;
#line 483 "gnome-pilot-conduit.c"
		}
		break;
	}
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::get_property"
{
	GnomePilotConduit *self G_GNUC_UNUSED;

	self = GNOME_PILOT_CONDUIT (object);

	switch (property_id) {
	case PROP_NAME:
	{	gchar *  ARG;
	memset (&ARG, 0, sizeof (gchar * ));
		{
#line 48 "gnome-pilot-conduit.gob"
ARG = self->name;
#line 517 "gnome-pilot-conduit.c"
		}
		g_value_set_string (VAL, ARG);
		break;
	}
	case PROP_PROGRESS_STEPPING:
	{	gint  ARG;
	memset (&ARG, 0, sizeof (gint ));
		{
#line 51 "gnome-pilot-conduit.gob"
ARG = self->progress_stepping;
#line 528 "gnome-pilot-conduit.c"
		}
		g_value_set_int (VAL, ARG);
		break;
	}
	case PROP_PROGRESS_TOP:
	{	gint  ARG;
	memset (&ARG, 0, sizeof (gint ));
		{
#line 54 "gnome-pilot-conduit.gob"
ARG = self->progress_top;
#line 539 "gnome-pilot-conduit.c"
		}
		g_value_set_int (VAL, ARG);
		break;
	}
	case PROP_PILOT:
	{	GPilotPilot *  ARG;
	memset (&ARG, 0, sizeof (GPilotPilot * ));
		{
#line 57 "gnome-pilot-conduit.gob"
ARG = self->pilot;
#line 550 "gnome-pilot-conduit.c"
		}
		g_value_set_pointer (VAL, ARG);
		break;
	}
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__


#line 48 "gnome-pilot-conduit.gob"
gchar * 
gnome_pilot_conduit_get_name (GnomePilotConduit * self)
#line 571 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::get_name"
{
#line 48 "gnome-pilot-conduit.gob"
		gchar* val; g_object_get (G_OBJECT (self), "name", &val, NULL); return val;
}}
#line 578 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__

#line 48 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_set_name (GnomePilotConduit * self, gchar * val)
#line 584 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::set_name"
{
#line 48 "gnome-pilot-conduit.gob"
		g_object_set (G_OBJECT (self), "name", val, NULL);
}}
#line 591 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__


#line 65 "gnome-pilot-conduit.gob"
GtkObject * 
gnome_pilot_conduit_new (void)
#line 598 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::new"
{
#line 66 "gnome-pilot-conduit.gob"
	
		GnomePilotConduit *retval = GET_NEW;
		return GTK_OBJECT (retval);
	}}
#line 607 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__

#line 71 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_progress (GnomePilotConduit * self, gint total, gint current)
#line 613 "gnome-pilot-conduit.c"
{
	GValue ___param_values[3];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 71 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 71 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 625 "gnome-pilot-conduit.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_INT);
	g_value_set_int (&___param_values[1], (gint ) total);

	___param_values[2].g_type = 0;
	g_value_init (&___param_values[2], G_TYPE_INT);
	g_value_set_int (&___param_values[2], (gint ) current);

	g_signal_emitv (___param_values,
		object_signals[PROGRESS_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
	g_value_unset (&___param_values[2]);
}

#line 75 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_send_progress (GnomePilotConduit * self, gint total, gint current)
#line 652 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::send_progress"
#line 75 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 75 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 659 "gnome-pilot-conduit.c"
{
#line 76 "gnome-pilot-conduit.gob"
	
		
		if (current > total) current = total;
		/* if stepping !=0, calc step, otherwise emit the signal */
		if (self->progress_stepping) {
			gfloat tot_f, cur_f;
			gint pct;
			gboolean emit = FALSE;

			tot_f = total;
			cur_f = current;
			pct = abs (cur_f / (tot_f / 100));

			if (pct < 1) {
				pct = 1;
			}

			if (pct < self->progress_top) {
				self->progress_top = 0;
				emit = TRUE;
			}
			if (pct >= self->progress_top + self->progress_stepping) {
				self->progress_top = pct;
				emit = TRUE;
			}

			if (emit) {
				self_progress (self, total, current);
			} 
		} if (self->progress_stepping==0) {
			self_progress (self, total, current);
		} else {
			/* stepping < 0 */
			return;
		}
	}}
#line 698 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__

#line 113 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_message (GnomePilotConduit * self, gchar * message)
#line 704 "gnome-pilot-conduit.c"
{
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 113 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 113 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 716 "gnome-pilot-conduit.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) message);

	g_signal_emitv (___param_values,
		object_signals[MESSAGE_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
}

#line 117 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_warning (GnomePilotConduit * self, gchar * message)
#line 738 "gnome-pilot-conduit.c"
{
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 117 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 117 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 750 "gnome-pilot-conduit.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) message);

	g_signal_emitv (___param_values,
		object_signals[WARNING_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
}

#line 121 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_error (GnomePilotConduit * self, gchar * message)
#line 772 "gnome-pilot-conduit.c"
{
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 121 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 121 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 784 "gnome-pilot-conduit.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) message);

	g_signal_emitv (___param_values,
		object_signals[ERROR_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
}

#line 125 "gnome-pilot-conduit.gob"
static void 
gnome_pilot_conduit_do_send_message (GnomePilotConduit * self, GPC_MessageType t, gchar * message, va_list ap)
#line 806 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::do_send_message"
#line 125 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 125 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 813 "gnome-pilot-conduit.c"
{
#line 127 "gnome-pilot-conduit.gob"
	
		gchar *tmp;
		
		tmp = g_strdup_vprintf(message,ap);
		
		switch (t) {
		case GPC_MSG:
			self_message (self, tmp);
			break;
		case GPC_ERR:
			self_error (self, tmp);
			break;
		case GPC_WARN:
			self_warning (self, tmp);
			break;
		}
		
		g_free(tmp);
		va_end(ap);		
	}}
#line 836 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__

#line 148 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_send_message (GnomePilotConduit * self, gchar * message, ...)
#line 842 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::send_message"
#line 148 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 148 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 849 "gnome-pilot-conduit.c"
{
#line 149 "gnome-pilot-conduit.gob"
	
		va_list ap;
		va_start (ap, message);
		self_do_send_message (self, GPC_MSG, message, ap);		
	}}
#line 857 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__

#line 154 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_send_warning (GnomePilotConduit * self, gchar * message, ...)
#line 863 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::send_warning"
#line 154 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 154 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 870 "gnome-pilot-conduit.c"
{
#line 155 "gnome-pilot-conduit.gob"
	
		va_list ap;
		va_start (ap, message);
		self_do_send_message (self, GPC_WARN, message, ap);
	}}
#line 878 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__

#line 160 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_send_error (GnomePilotConduit * self, gchar * message, ...)
#line 884 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::send_error"
#line 160 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 160 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 891 "gnome-pilot-conduit.c"
{
#line 161 "gnome-pilot-conduit.gob"
	
		va_list ap;
		va_start (ap, message);
		self_do_send_message (self, GPC_ERR, message, ap);
	}}
#line 899 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__

#line 167 "gnome-pilot-conduit.gob"
int 
gnome_pilot_conduit_create_settings_window (GnomePilotConduit * self, GtkWidget * parent)
#line 905 "gnome-pilot-conduit.c"
{
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 167 "gnome-pilot-conduit.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 167 "gnome-pilot-conduit.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT (self), (int )0);
#line 917 "gnome-pilot-conduit.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) parent);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[CREATE_SETTINGS_WINDOW_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}
#line 167 "gnome-pilot-conduit.gob"
static int 
___real_gnome_pilot_conduit_create_settings_window (GnomePilotConduit * self G_GNUC_UNUSED, GtkWidget * parent)
#line 946 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::create_settings_window"
{
#line 168 "gnome-pilot-conduit.gob"
	
		return -1;
	}}
#line 954 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__

#line 171 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_display_settings (GnomePilotConduit * self)
#line 960 "gnome-pilot-conduit.c"
{
	GValue ___param_values[1];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 171 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 171 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 972 "gnome-pilot-conduit.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	g_signal_emitv (___param_values,
		object_signals[DISPLAY_SETTINGS_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
}

#line 172 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_save_settings (GnomePilotConduit * self)
#line 989 "gnome-pilot-conduit.c"
{
	GValue ___param_values[1];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 172 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 172 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 1001 "gnome-pilot-conduit.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	g_signal_emitv (___param_values,
		object_signals[SAVE_SETTINGS_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
}

#line 173 "gnome-pilot-conduit.gob"
void 
gnome_pilot_conduit_revert_settings (GnomePilotConduit * self)
#line 1018 "gnome-pilot-conduit.c"
{
	GValue ___param_values[1];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 173 "gnome-pilot-conduit.gob"
	g_return_if_fail (self != NULL);
#line 173 "gnome-pilot-conduit.gob"
	g_return_if_fail (GNOME_IS_PILOT_CONDUIT (self));
#line 1030 "gnome-pilot-conduit.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	g_signal_emitv (___param_values,
		object_signals[REVERT_SETTINGS_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
}

#line 175 "gnome-pilot-conduit.gob"
const gchar * 
gnome_pilot_conduit_get_base_dir (GnomePilotConduit * self)
#line 1047 "gnome-pilot-conduit.c"
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit::get_base_dir"
#line 175 "gnome-pilot-conduit.gob"
	g_return_val_if_fail (self != NULL, (const gchar * )0);
#line 175 "gnome-pilot-conduit.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT (self), (const gchar * )0);
#line 1054 "gnome-pilot-conduit.c"
{
#line 176 "gnome-pilot-conduit.gob"
	
		/* FIXME: yuch! This preserves some sanity, but it should go
		   away once all conduits have been converted to the new loader */
		if (self->pilot == NULL) {
			return g_get_home_dir ();
		}
		return self->pilot->sync_options.basedir;
	}}
#line 1065 "gnome-pilot-conduit.c"
#undef __GOB_FUNCTION__
